### ISSUE TITLE
Productionize the `SymbolRank` Overview construction

### ISSUE THREAD

**Issue by emrgnt-cmplxty** [emrgnt-cmplxty/automata#72]
An overview of the local repository can be created based on the output from SymbolRank. SymbolRank is necessary to avoid having to print every symbol in the codebase when providing an overview of the important bits of the codebase.

The resulting output looks something like this

```bash
An overview of the important python modules, and their internal functions and classes follows below.

cli.scripts.run_doc_embedding_l2.main
cli.scripts.run_doc_embedding_l3.main
cli.scripts.run_doc_post_process.main
config.agent_config_builder.AutomataAgentConfigBuilder
config.agent_config_builder.AutomataAgentConfigBuilder._validate_type
config.agent_config_builder.AutomataAgentConfigFactory
config.agent_config_builder.AutomataAgentConfigFactory.create_config
config.config_types.AgentConfigName
config.config_types.AutomataAgentConfig
config.config_types.AutomataAgentConfig.load
core.agent.action.Action
...
```

This output is produced by this following snippet -

```python
    class TemplateFormatter:
        @staticmethod
        def create_default_formatter(
            config: "AutomataAgentConfig", max_default_overview_symbols: int = 100
        ) -> Dict[str, str]:
            """
            Create a default template formatter.

            Args:
                config (AutomataAgentConfig): The AutomataAgentConfig to use.

            Returns:
                Dict[str, str]: The default template formatter.

            Raises:
                NotImplementedError: If the config_name is not supported.

            TODO:
                - Consider how we might implement dependency injection across this call stack
                - Replace symbol_search with symbol_rank when it is implemented on DependencyFactory
            """
            formatter = {}
            if config.config_name == AgentConfigName.AUTOMATA_READER:
                from automata.core.agent.tools.tool_utils import DependencyFactory

                symbol_search = DependencyFactory().get("symbol_search")
                symbol_rank = symbol_search.symbol_rank
                ranks = symbol_rank.get_ranks()
                symbol_dotpaths = [
                    ".".join(symbol.dotpath.split(".")[1:])
                    for symbol, _ in ranks[:max_default_overview_symbols]
                ]
                formatter["symbol_rank_overview"] = "\n".join(sorted(symbol_dotpaths))
```

This is a rather unelegant approach to solving this problem. Some more thought should be put into where TemplateFormatter should live and how the logic to calculate the symbol_rank_overview should be implemented.

As always, don't hesitate to ask if you have any questions or need further clarification. Your contributions to this project are highly valued!

**Comment by emrgnt-cmplxty** [comment]
## Proposed Solution
### New Code Implementation

This following draft illustrates the points mentioned above:

```python
from typing import List, Tuple
from automata.core.symbol.symbol_types import Symbol

class SymbolRank:
    ...
    def get_top_symbols(self, n: int) -> List[Tuple[str, float]]:
        """
        Get the top N symbols according to their ranks.
        
        Args: 
            n: The number of top symbols to retrieve.
        
        Returns:
            A list of tuples each containing the dotpath of a symbol and its rank.
        """
        ranks = self.get_ranks()
        top_symbols = [
            (".".join(symbol.dotpath.split("."[1:]), rank)
            for symbol, rank in ranks[:n]
        ]
        
        return top_symbols


class TemplateFormatter:
    ...
    @staticmethod
    def create_default_formatter(
        config: "AutomataOpenAIAgentConfig", symbol_rank: 'SymbolRank', max_default_overview_symbols: int = 100
    ) -> Dict[str, str]:
        """
        TODO:
            - Re-implement this method after the new instruction configs are finalized.
        """
        formatter: Dict[str, str] = {}
        if config.config_name == var_config_names.DOCSTRING_GENERATION:
            top_symbols = symbol_rank.get_top_symbols(max_default_overview_symbols)
            formatter["ranked_symbols_overview"] = "\n".join(
                f"[{rank:.3f}] {symbol}" for symbol, rank in sorted(top_symbols, key=lambda x: x[1], reverse=True)
            )
        elif config.config_name == AgentConfigName.TEST:
            pass
        else:
            raise NotImplementedError("Automata does not have a default template formatter.")

        return formatter
```

Note that the `SymbolRank` instance is passed as an argument to the `create_default_formatter`. This new approach makes the `SymbolRank` instance a dependency for `create_default_formatter`, which follows the Dependency Inversion Principle. 

Remember that this is a rough draft strategy to guide your implementation based on a comprehension of your requirements and the `SymbolRank` and `TemplatingFormatter` classes. It is suggested that this strategy be considerably validated and iteratively refined using unit tests and other validation methods before it is productionized.

**Comment by gravitronics** [comment]
## Proposed Solution
The current code snippet works as follows:

1. It creates an instance of `SymbolSearch` to access the `SymbolRank` instance in its attribute.
2. The ranks and corresponding symbols in the software codebase are extracted using `get_ranks()` from the `SymbolRank` instance.
3. Dot-paths of the top N symbols sorted by rank are prepared. These dot-paths are a way of representing the full path to the symbol in the structure of the Python project.
4. Finally, it produces a list of the top N symbols, sorted by their respective ranks.

To address your concerns and make the solution more cohesive, we suggest the following:

1. Instead of accessing the `SymbolRank` instance indirectly through `SymbolSearch`, we'd instantiate and use `SymbolRank` directly. This improves the separation of responsibilities because `SymbolSearch` should be dedicated to searching symbols, and it shouldn't have to handle `SymbolRank`.

2. As per your note of following the Dependency Injection principle, the `SymbolRank` instance should be injected into the `TemplateFormatter` instead of it creating its own. By doing this, we'll have the flexibility of modifying the `SymbolRank` context without much interconnection and complication. 

3. We could also add a function in `SymbolRank` that abstracts the process of getting a list of top N symbols. It will make the code in `TemplateFormatter` cleaner and more readable, and follow the single responsibility principle.

### New Code Implementation

This following draft illustrates the points mentioned above:

```python
from typing import List, Tuple
from automata.core.symbol.symbol_types import Symbol

class SymbolRank:
    ...
    def get_top_symbols(self, n: int) -> List[Tuple[str, float]]:
        """
        Get the top N symbols according to their ranks.
        
        Args: 
            n: The number of top symbols to retrieve.
        
        Returns:
            A list of tuples each containing the dotpath of a symbol and its rank.
        """
        ranks = self.get_ranks()
        top_symbols = [
            (".".join(symbol.dotpath.split("."[1:]), rank)
            for symbol, rank in ranks[:n]
        ]
        
        return top_symbols


class TemplateFormatter:
    ...
    @staticmethod
    def create_default_formatter(
        config: "AutomataOpenAIAgentConfig", symbol_rank: 'SymbolRank', max_default_overview_symbols: int = 100
    ) -> Dict[str, str]:
        """
        TODO:
            - Re-implement this method after the new instruction configs are finalized.
        """
        formatter: Dict[str, str] = {}
        if config.config_name == var_config_names.DOCSTRING_GENERATION:
            top_symbols = symbol_rank.get_top_symbols(max_default_overview_symbols)
            formatter["ranked_symbols_overview"] = "\n".join(
                f"[{rank:.3f}] {symbol}" for symbol, rank in sorted(top_symbols, key=lambda x: x[1], reverse=True)
            )
        elif config.config_name == AgentConfigName.TEST:
            pass
        else:
            raise NotImplementedError("Automata does not have a default template formatter.")

        return formatter
```

Note that the `SymbolRank` instance is passed as an argument to the `create_default_formatter`. This new approach makes the `SymbolRank` instance a dependency for `create_default_formatter`, which follows the Dependency Inversion Principle. 

Remember that this is a rough draft strategy to guide your implementation based on a comprehension of your requirements and the `SymbolRank` and `TemplatingFormatter` classes. It is suggested that this strategy be considerably validated and iteratively refined using unit tests and other validation methods before it is productionized.
